#!/bin/sh

rm -vf Makefile config.h config.log config.status stamp-h1
rm -vRf autom4te.cache

rm -vf *~

rm -vf uget-integration-host-*.tar.gz uget-integration-host-*.deb uget-integration-host-*.rpm

rm -vRf src/.deps
rm -vf src/Makefile src/uget-integration-host src/uget-integration-host.exe src/uget-integration-host.o src/com.ugetdm.integration.json
